name: Github Actions Example

on:
  pull_request:
  push:
    branches:
      - main
      
jobs:
  run-shell-command:
    name: Running Basics commands
    runs-on: ubuntu-latest
    steps:    
    - name: Echo somes strings
      run: |
        echo "Tis is a test string"    
        echo "Tis is a test string 1"      
    - name: multiline script
      run: |
        npm test
        node -v
        npm -v
        date
        cal
        pwd
        cat /etc/*release
      
