name: Github Actions Example

on:
  pull_request:
  push:
    branches:
      - main
      
jobs:
  run-shell-command:
    name: Running Basics commands
    runs-on: ubuntu-latest
    steps:    
    - name: Echo somes strings
      run: |
        echo "This is a test string"    
        echo "This is a test string 1"      
    - name: multiline script
      run: |        
        node -v
        npm -v
        
        
        
      
      
